### ISSUE TITLE
add ovms sample image download into run script

### ISSUE THREAD

**Issue by vli11** [intel-retail/automated-self-checkout#124]
## Version

What release version was the issue found in? 1.5.0

## Hardware configuration

11th Gen Intel® Core™ i7 with Mesa Intel®Xe Graphics

## Describe the bug

add ovms sample image download process into run script so user doesn't need to run downloading image manually

## To Reproduce

1. go to automated-self-checkout/configs/opencv-ovms/images/, there is no image file

**Comment by jim-wang-intel** [comment]
@vli11  probably doesn't want to download every time if the sample image already exists. This is to save downloading time.
