### ISSUE TITLE
Pipeline Run with core option does not generate any result

### ISSUE THREAD

**Issue by brian-intel** [intel-retail/automated-self-checkout#15]
even with core as option, docker run is referencing arc folder
"-c framework-pipelines/arc/yolov5s_full.sh"

addl info: vaapi decode bin is not present

docker run --network host --privileged --user root --ipc=host --name vision-self-checkout0 -e RENDER_MODE= -e INPUTSRC_TYPE=FILE -e DISPLAY=:0 -e cl_cache_dir=/home/pipeline-server/.cl-cache -v /home/user1/retail.vision-self-checkout-demo-master/.cl-cache:/home/pipeline-server/.cl-cache -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/user1/retail.vision-self-checkout-demo-master/sample-media/:/home/pipeline-server/vids -v /home/user1/retail.vision-self-checkout-demo-master/configs/pipelines:/home/pipeline-server/pipelines -v /home/user1/retail.vision-self-checkout-demo-master/configs/extensions:/home/pipeline-server/extensions -v /home/user1/retail.vision-self-checkout-demo-master/results:/tmp/results -v /home/user1/retail.vision-self-checkout-demo-master/configs/models/2022:/home/pipeline-server/models -v /home/user1/retail.vision-self-checkout-demo-master/configs/framework-pipelines:/home/pipeline-server/framework-pipelines -w /home/pipeline-server -e BARCODE_RECLASSIFY_INTERVAL=5 -e OCR_RECLASSIFY_INTERVAL=5 -e OCR_DEVICE=CPU -e LOG_LEVEL= -e GST_DEBUG=0 -e decode_type=vaapidecodebin -e pre_process=pre-process-backend=vaapi-surface-sharing -e pre-process-config=VAAPI_FAST_SCALE_LOAD_FACTOR=1 -e LOW_POWER= -e cid_count=0 -e inputsrc=filesrc location=vids/5-Bottles-short.mp4 ! qtdemux ! h264parse -itd -e CPU_ONLY= -e AUTO_SCALE_FLEX_140= --rm sco-soc:2.0 bash -c framework-pipelines/arc/yolov5s_full.sh

sudo ./docker-run.sh --platform core --inputsrc file:5-Bottles-short.mp4

tried rtsp stream also as input but same result.
Is it right to have this option(../arc/..) even for core? - "-c framework-pipelines/arc/yolov5s_full.sh"

not tried benchmark yet

**Comment by brian-intel** [comment]
Need to verify with Arc system

**Comment by vli11** [comment]
verified with Arc system, I could reproduce the problem, but not sure platform=core running pipeline on Arc system is something we are going to support

**Comment by vli11** [comment]
This is not a bug, but enhancement now
