### ISSUE TITLE
Fail to get memory bandwidth value

### ISSUE THREAD

**Issue by dino945** [intel-retail/automated-self-checkout#229]
## Version
Main branch

## Hardware configuration
Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz with Intel® Data Center GPU Flex 140 and Intel® Data Center GPU Flex 170

## Describe the bug
Unable to get memory bandwidth value due to empty port value
![image](https://github.com/intel-retail/automated-self-checkout/assets/103552280/a62aede6-c41f-4e01-9c4e-d83e7b2f1db2)

![image](https://github.com/intel-retail/automated-self-checkout/assets/103552280/9aec050f-06f3-44ea-9feb-25e53e6444e4)

No memory bandwidth value after consolidate
![image](https://github.com/intel-retail/automated-self-checkout/assets/103552280/6b9b1fd4-87be-4ff1-a623-39e1f2530b75)

## To Reproduce
1. cd automated-self-checkout/benchmark-scripts
2. run with default config provided
3. PIPELINE_PROFILE="grpc_python" RENDER_MODE=0 sudo -E ./benchmark.sh --workload opencv-ovms --pipelines 1 --logdir testRun/run0 --init_duration 30 --duration 60 --platform dgpu --inputsrc rtsp://127.0.0.1:8554/camera_0
4. error appear in second run

**Comment by jim-wang-intel** [comment]
Hi @dino945 [this PR](https://github.com/intel-retail/automated-self-checkout/pull/233) should fix the issue above
