### ISSUE TITLE
Fail to get memory bandwidth value

### ISSUE THREAD

**Issue by dino945** [intel-retail/automated-self-checkout#234]
## Version
Main branch

## Hardware configuration
Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz with Intel® Data Center GPU Flex 140 and Intel® Data Center GPU Flex 170

## Describe the bug
Reopen issue due to new bug found after applying fix from [#229 ](url)

Issue#1:
<img width="878" alt="image" src="https://github.com/intel-retail/automated-self-checkout/assets/103552280/b8a58731-d9b0-4a33-9a88-d535ccdceab6">

Few changes being made to resolve Issue#1:
Remove "/" in front $cpuOutputDir  
New command: docker run -itd -v $SOURCE_DIR/$LOG_DIRECTORY:$cpuOutputDir  --cap-drop ALL --cap-add CAP_SYS_ADMIN --user root -e XPUM_REST_NO_TLS=1 -e XPUM_EXPORTER_NO_AUTH=1 -e XPUM_EXPORTER_ONLY=1 --publish 127.0.0.1:$xpumPort:$xpumPort --device /dev/dri:/dev/dri --name=xpummemory intel/xpumanager:v1.0.0

Move cpuOutputDir to remove empty directory issue
<img width="517" alt="image" src="https://github.com/intel-retail/automated-self-checkout/assets/103552280/7daf214b-db7f-4d82-a8f6-87e562337523">

Issue#2: Command not found
<img width="360" alt="image" src="https://github.com/intel-retail/automated-self-checkout/assets/103552280/b814fb8c-9797-46aa-8583-17730285b4b5">

## To Reproduce
1. cd automated-self-checkout/benchmark-scripts
2. run with default config provided
3. PIPELINE_PROFILE="grpc_python" RENDER_MODE=0 sudo -E ./benchmark.sh --workload opencv-ovms --pipelines 1 --logdir testRun/run0 --init_duration 30 --duration 60 --platform dgpu --inputsrc rtsp://127.0.0.1:8554/camera_0
4. error appear in second run

**Comment by jim-wang-intel** [comment]
Hi @dino945  [this PR](https://github.com/intel-retail/automated-self-checkout/pull/236) should resolve both issues abovementioned, please test it with Xeon platform and let us know.
