### ISSUE TITLE
GPU Utilization 0 with target device MULTI:GPU.0,CPU using instance_segmentation_omz_1040 model

### ISSUE THREAD

**Issue by sbin149x** [intel-retail/automated-self-checkout#235]
## Version

Main Branch

## Hardware configuration

- Intel(R) Xeon(R) Platinum 8480+ with Intel® Data Center GPU Flex 170 x3

## Describe the bug

GPU utilization is 0 when the target device is MULTI:GPU.0,CPU for instance_segmentation_omz_1040 model.
Didn't encounter this issue when changing the model to yolov5s and bit_64 or when running instance_segmentation_omz_1040 model with GPU.0 device alone.

instance_segmentation_omz_1040 with MULTI:GPU.0,CPU data:
![image](https://github.com/intel-retail/automated-self-checkout/assets/99851971/969049f3-2410-483c-9863-3f9bc37b2000)

instance_segmentation_omz_1040 with GPU.0 data:
![image](https://github.com/intel-retail/automated-self-checkout/assets/99851971/3cf65034-9425-4028-b776-e0baaa07df64)

yolov5s with MULTI:GPU.0,CPU data:
![image](https://github.com/intel-retail/automated-self-checkout/assets/99851971/c40001ad-a340-4dec-97cf-42fd9f2de88b)

bit_64 with MULTI:GPU.0,CPU data:
![image](https://github.com/intel-retail/automated-self-checkout/assets/99851971/3c8849bc-f893-4973-a568-3a7c989fa34a)

## To Reproduce

1. cd automated-self-checkout/benchmark-scripts
2. Run with default config provided but change the target device to "MULTI:GPU.0,CPU"
3. Modify the /configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml accordingly
4. PIPELINE_PROFILE="grpc_python" RENDER_MODE=0 sudo -E ./benchmark.sh --workload opencv-ovms --pipelines 3 --logdir testRun/gpu0_grpc_python/run1 --init_duration 30 --duration 60 --platform dgpu.0 --inputsrc rtsp://127.0.0.1:8554/camera_0

**Comment by brian-intel** [comment]
Retest using Device="MULTI:GPU.0,CPU"

**Comment by antoniomtz** [comment]
I did some troubleshooting and the correct value for **DEVICE** should be "MULTI:GPU,CPU" and letting --platform to decide which gpu we want to use, either --platform gpu.0 or gpu.1

**Comment by antoniomtz** [comment]
I did swap the igt filename to align better with the corresponding GPU.0 or GPU.1
