### ISSUE TITLE
GPU usage=0% for DGPU device

### ISSUE THREAD

**Issue by siewkee945** [intel-retail/automated-self-checkout#256]
## Version
Main branch (Git clone on 22 August 2023)

## Hardware configuration
PE3000G [12th Gen Intel(R) Core(TM) i7-12800HE with Intel® Arc ™ A370M Graphics (Alchemist)]

## Describe the bug
GPU usage of DGPU is shown as 0% despite number of streams being run
Result when running --platform dgpu.1
<img width="285" alt="image" src="https://github.com/intel-retail/automated-self-checkout/assets/103552280/8dfe4fe8-9ca9-441d-a829-b117175d63ee">

Try to verify if benchmark:igt being build correctly by running --platform dgpu.0
Able to get reasonable GPU usage value
<img width="284" alt="image" src="https://github.com/intel-retail/automated-self-checkout/assets/103552280/d648c1d2-d637-42df-9a46-b56c99ae7c65">

## To Reproduce
1. cd benchmark-scripts
2. sudo -E ./benchmark.sh --performance_mode powersave --pipelines 5 --logdir testRun/5stream/run0 --duration 120 --init_duration 60 --platform dgpu.1 --barcode_disabled --ocr_disabled --inputsrc rtsp://127.0.0.1:8554/camera_0
3. make consolidate ROOT_DIRECTORY=testRun/5stream
4. GPU usage is 0%

**Comment by brian-intel** [comment]
Reset with GST profile and Arc GPU

**Comment by jim-wang-intel** [comment]
WIP:  doing tests on Serpent Canyon

**Comment by jim-wang-intel** [comment]
@brian-intel for ARC this may be due to unable to load the object detection model by OpenVINO model server for some reason: could be some driver missing for ARC dGPU on OVMS side.

**Comment by jim-wang-intel** [comment]
discussed with @brian-intel and we will put this as known issue and documented in the Release Note for 2.0 release

**Comment by antoniomtz** [comment]
I did some investigation and looks like the consolidate script is not parsing the correct value for DGPU which is the '[unknown]' value used by intel_gpu_top. That is the value for the DGPU usage. 

the igt0.json file is correctly monitoring the DGPU usage and I can see values in the [unknown] fields.

**Comment by antoniomtz** [comment]
I found a confusion here. 
On the system level /dev/dri/card0 is the Integrated GPU, and /dev/dri/card1 is DGPU Arc 
However, using the IGT (intel_gpu_top) utility, it reports DGPU as 0 and iGPU as 1, hence, on the report, GPU_1 is iGPU and GPU_0 is DGPU. 

I also noticed that the value used to compute the DGPU utilization is not the correct one. I will open a PR for that.
