### ISSUE TITLE
Build profile launcher inside docker container

### ISSUE THREAD

**Issue by antoniomtz** [intel-retail/automated-self-checkout#293]
Build profile launcher inside docker container so the end user doesn't have to install golang on localhost as prerequisite.

**Comment by jim-wang-intel** [comment]
@antoniomtz  this issue seems conflicts with this closed issue: https://github.com/intel-retail/automated-self-checkout/issues/263  

we need some discussion please

**Comment by antoniomtz** [comment]
@jim-wang-intel Profile-launcher will remain as native executable. But the building process will take place inside docker. This will eliminate the need of installing golang on localhost.

**Comment by jim-wang-intel** [comment]
> @jim-wang-intel Profile-launcher will remain as native executable. But the building process will take place inside docker. This will eliminate the need of installing golang on localhost.

got cha, thanks for this great enhancement.
