### ISSUE TITLE
Documentation of the solution to help customize benchmark configurations

### ISSUE THREAD

**Issue by kkvp1** [intel-retail/automated-self-checkout#30]
Apart from the steps to run the existing benchmark scripts, more documentation on the solution flow, organization of files etc will help run pipelines/configs/models not covered in existing scripts.

**Comment by brian-intel** [comment]
Update index diagram to show volume mounts
Update pipelinesetup to add model location note for modeldownload.sh

**Comment by brian-intel** [comment]
Add architecture page that links to the architecture documentation https://github.com/intel-retail/documentation/tree/main/Architecture
