### ISSUE TITLE
bug: running instance_segmentation or object_detection without RENDER_MODE input caused xcb error

### ISSUE THREAD

**Issue by vli11** [intel-retail/automated-self-checkout#300]
## Version

What release version was the issue found in? 1.6.0

## Hardware configuration

all

## Describe the bug

when running instance_segmentation or object_detection without RENDER_MODE input, it will failed the pipeline run with below error: 

[ INFO ] Connecting to remote model: localhost:9000/models/instance-segmentation-security-1040
[ INFO ] 	Input layer: image, shape: [1, 608, 608, 3], precision: FP32, layout: NHWC
[ INFO ] 	Output layer: 3523, shape: [-1, 5], precision: FP32, layout: 
[ INFO ] 	Output layer: masks, shape: [-1, 28, 28], precision: FP32, layout: 
[ INFO ] 	Output layer: 3524, shape: [-1], precision: I64, layout: 
Authorization required, but no authorization protocol specified
qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

when running script command without RENDER_MODE=1, the default would be 0, in such case, we wouldn't need to trigger the UI or the xcb error above

## To Reproduce
in a clean box,
1. make build-ovms-server
2. make build-grpc-python
3. make build-python-apps
4. ./camera-simulator/camera-simulator.sh
5. PIPELINE_PROFILE="object_detection" sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
6. go to r0.jsonl file under results/, you will see above error

**Comment by brian-intel** [comment]
Add workaround in troubleshooting.md

**Comment by jim-wang-intel** [comment]
Re-tested and unable to reproduce the xcb error behavior either for object_detection profile nor instance_segmentation profile. 

 This old issue may have already been fixed from past commits.

close the issue.
