### ISSUE TITLE
QuickStart - Add closing instructions

### ISSUE THREAD

**Issue by vmilhoan** [intel-retail/automated-self-checkout#316]
## Version

1.5.0

## Hardware configuration

12th Gen Intel® Core™ i7 with Intel® Arc™ A770M Graphics (Serpent Canyon)

## Describe the bug

On the quick start guide (https://github.com/intel-retail/automated-self-checkout), suggest add instructions after step 4 showing how to stop the demo (it keeps running in the browser, and then when the browser is closed it starts it again).

**Comment by antoniomtz** [comment]
@vmilhoan Step 5 is to stop the entire demo with the command `make clean-all`
