### ISSUE TITLE
./profile-launcher: No such file or directory

### ISSUE THREAD

**Issue by wallace-lee** [intel-retail/automated-self-checkout#361]
## Version

main line, most recent commit id: 11596af4422a986251dace75dd9bdd3dcd557111

## Hardware configuration

- ADL-PS SDM

## Describe the bug

able to build the code according to the readme, but unable to execute the pipeline successfully.
results/profile-launcher*.log contained following message:

./run-ovms.sh: line 103: ./profile-launcher: No such file or directory

It is also observed using ls command that the profile-launcher symlink to the configs/opencv-ovms/cmd_client/profile-launcher is broken.

## To Reproduce

make build-grpc-go
PIPELINE_PROFILE="grpc_python" sudo -E ./run.sh --workload ovms --platform core --inputsrc /dev/video0
check log file in the ./results folder.

**Comment by jim-wang-intel** [comment]
@wallace-lee  the steps in reproduce is a bit mismatch: you built `grpc-go` but then you ran with grpc_python profile.

Please do `make build-grpc-python` if you want to run grpc-python pipeline profile.

**Comment by jim-wang-intel** [comment]
@wallace-lee  
Regarding your comments on " It is also observed using ls command that the profile-launcher symlink to the configs/opencv-ovms/cmd_client/profile-launcher is broken."

Please remove the broken symbolic link manually and re-build profile-launcher with login user like your local user:
1. sudo unlink ./profile-launcher    (**verify that the symbolic link is removed**)
2. run `make build-profile-launcher`  (**verify that the symbolic link .profile-launcher is successfully created**)

**Comment by wallace-lee** [comment]
@jim-wang-intel thanks for the recommendation. The issue is now resolved. The issue was caused by docker installed via snap (it seems like the code has problem with overlay2 storage-driver which is the default with snap) - see https://stackoverflow.com/questions/72564830/python3-minimal-error-during-pip-installation-in-docker-build-permissionerro

Thanks for your help.

**Comment by jim-wang-intel** [comment]
> @jim-wang-intel thanks for the recommendation. The issue is now resolved. The issue was caused by docker installed via snap (it seems like the code has problem with overlay2 storage-driver which is the default with snap) - see https://stackoverflow.com/questions/72564830/python3-minimal-error-during-pip-installation-in-docker-build-permissionerro
> 
> Thanks for your help.

Hi @wallace-lee  thanks for your feedback about the docker installed via snap.  We can add that into trouble shooting guide in documentation for reference.  Thanks a lot and have wonderful weekend.
