### ISSUE TITLE
Keep documentation current with code/functionality

### ISSUE THREAD

**Issue by vmilhoan** [intel-retail/automated-self-checkout#363]
## Version
Latest

## Hardware configuration
Serpent Canyon NUC

## Describe the bug
I had a difficult time getting benchmarks completed, the documentation may be out of date given the current state of the source base refactoring. I received some one-on-one help to run the right commands. This isn't just a specific bug, but a suggestion to look at the process and release documentation that matches the code functionality at the same time as releasing the code (users are likely to pull 'latest')

## To Reproduce
git clone 'latest'
build and run the performance commands - they fail

**Comment by brian-intel** [comment]
Add tag to quckstart guide
