### ISSUE TITLE
Performance Data - GPU vs CPU

### ISSUE THREAD

**Issue by vmilhoan** [intel-retail/automated-self-checkout#364]
## Version
latest as of Oct 25th

## Hardware configuration
Serpent Canyon NUC

## Describe the bug

When I ran the benchmarks, I ran first on CPU (stream density) and the result was 4 camera streams. Switching over to GPU, the stream density went down to 3. I would think GPU would be better stream density.

It was explained to me that performance varies based on the model ran, which is OK. And I suppose explaining all of this might be outside of the scope of this source base. However, I realized that the published performance data is we don't publish results just on CPU to show some of these comparisons. Suggest adding more test cases to the data. Perhaps with some explanation of the discrepancies.

## To Reproduce

Ran using this command with a mix of core and gpu platform options

PIPELINE_PROFILE="object_detection" RENDER_MODE=0 sudo -E ./benchmark.sh --stream_density 14.95  --logdir object_detection/data --duration 120 --init_duration 40 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_1

**Comment by brian-intel** [comment]
Update document to explain how to change model percision
