### ISSUE TITLE
Bottle probability lower than expected.

### ISSUE THREAD

**Issue by vmilhoan** [intel-retail/automated-self-checkout#365]
## Version

latest as of Oct 25th

## Hardware configuration

Serpent Canyon NUC

## Describe the bug

When showing the rendering and running the pipeline for the Coke bottles demo, it was pointed out that the probability number for the coke bottle in the front (the larger, clearer bottle) was lower than the probability number for the bottles in the background (smaller/blurry). It was about 65% vs 95% range. This is unexpected, perhaps we can include an explanation or understand if there's something wrong or is the model not trained for this video content.

**Comment by brian-intel** [comment]
object_detection profile

**Comment by brian-intel** [comment]
Out of scope. This is model specific
