### ISSUE TITLE
Confusing Hardware Setup Steps

### ISSUE THREAD

**Issue by kk-vp** [intel-retail/automated-self-checkout#366]
## Version
1.5.0
## Hardware configuration
NA
## Describe the bug
In hardware setup steps, (https://intel-retail.github.io/automated-self-checkout/hardwaresetup.html)
for Core and Arc, Ubuntu 20 is specified
for Xeon and Flex Ubuntu 22 is specified
--does it mean only 20 is supported for Core and only 22 is supported for Xeon?

Also it is not organized right. ARC should ideally be a sub category under Core and not a separate heading at same category level as core. same for Xeon Flex too.
## To Reproduce
Examine data at https://intel-retail.github.io/automated-self-checkout/hardwaresetup.html)
1. Go to https://intel-retail.github.io/automated-self-checkout/hardwaresetup.html)

**Comment by jim-wang-intel** [comment]
Hi @kk-vp 

you mentioned "Also it is not organized right. ARC should ideally be a sub category under Core and not a separate heading at same category level as core. same for Xeon Flex too."

The Core tab means Core CPU processor and ARC is a discrete GPU processor and we would like to treat them as different hardware setup as they serve different use cases and setup.

As far as the version of Ubuntu support, they are related to Linux kernel updates and the documentation probably is out of date; so we will fix that if they are.

**Comment by brian-intel** [comment]
Need to verify Ubuntu 22.04 with Arc
