### ISSUE TITLE
Link to Depreciated page

### ISSUE THREAD

**Issue by kk-vp** [intel-retail/automated-self-checkout#367]
## Version
1.5.0
## Hardware configuration
Arc GPU
## Describe the bug
Link in Hardware Setup points to Depreciated page
https://intel-retail.github.io/automated-self-checkout/hardwaresetup.html
 - Update the [Kernel](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal-arc.html)
## To Reproduce
https://intel-retail.github.io/automated-self-checkout/hardwaresetup.html
 - Update the [Kernel](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal-arc.html)
1. Go to https://intel-retail.github.io/automated-self-checkout/hardwaresetup.html
 - Update the [Kernel](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal-arc.html)

**Comment by jim-wang-intel** [comment]
related to issue #366

**Comment by jim-wang-intel** [comment]
@brian-intel  should we change all the ubuntu version from 20.04 to 22.04 (**At least for those GPU use cases**)?  it seems to me from the GPU data center documentation; they support version 22.04: https://dgpu-docs.intel.com/driver/client/overview.html

**Comment by brian-intel** [comment]
Test with 2022 on Arc and determine if we remove 2020 support.

**Comment by ejlee3** [comment]
closed by #497
