### ISSUE TITLE
download_models/getModels.sh --workload ovms fails

### ISSUE THREAD

**Issue by kk-vp** [intel-retail/automated-self-checkout#369]
## Version
1.5.0
## Hardware configuration
12th Gen Intel® Core™ i7 with Intel® Arc™ A770M Graphics

## Describe the bug

running "getModules.sh --workload ovms" exactly as per documentation generates following error

workload: ovms
./getModels.sh: 35: [: ovms: unexpected operator
ERROR: "--workload" requires an argument dlstreamer|ovms

## To Reproduce
automated-self-checkout/download_models$ sh ./getModels.sh --workload ovms
workload: ovms
./getModels.sh: 35: [: ovms: unexpected operator
ERROR: "--workload" requires an argument dlstreamer|ovms

**Comment by jim-wang-intel** [comment]
when just ran with `./getModels.sh --workload ovms` it works since the script itslef is bash executable and there is script binary directive in the first line of the script;
We should fix the documentation to remove `sh` when mentioned how to run this.

**Comment by jim-wang-intel** [comment]
Hi @kk-vp, this is  a documentation issue: PR #373 should resolve this. Thanks.
