### ISSUE TITLE
make build-ovms-server does not create all required images

### ISSUE THREAD

**Issue by kk-vp** [intel-retail/automated-self-checkout#370]
## Version
1.5.0
## Hardware configuration
12th Gen Intel® Core™ i7 with Intel® Arc™ A770M Graphics
## Describe the bug
"make build-ovms-server" should have created five docker images as per the documentation
But only "openvino/model_server   2023.1-gpu" is created
There are no errors reported in log
The log is attached below.
(also just tried running the pipeline, but no output generated which was expected due to the above)

## To Reproduce
Follow Setup Pipeline Documentation
https://intel-retail.github.io/automated-self-checkout/OVMS/pipelinesetup.html
executed Step 7 : make build-ovms-server
===================Log=============
:::::Try 1::::
admin@DemoSystem-NUC12SNKi72:~/automated-self-checkout$ sudo make build-ovms-server
HTTPS_PROXY= HTTP_PROXY= docker pull openvino/model_server:2023.1-gpu
2023.1-gpu: Pulling from openvino/model_server
44ba2882f8eb: Pull complete 
896ce74507fa: Pull complete 
dd75c02ca881: Pull complete 
20f2f2665fbc: Pull complete 
4f4fb700ef54: Pull complete 
b80c0865db0e: Pull complete 
35378d510508: Pull complete 
Digest: sha256:1da7d5e1b5ce1373f3da44c1e6e82b49803178acfdf06a24e692041fee665fc1
Status: Downloaded newer image for openvino/model_server:2023.1-gpu
docker.io/openvino/model_server:2023.1-gpu
sudo docker build --build-arg HTTPS_PROXY= --build-arg HTTP_PROXY= -f configs/opencv-ovms/models/2022/Dockerfile.updateDevice -t update_config:dev configs/opencv-ovms/models/2022/.
[+] Building 3.7s (9/9) FINISHED                                                                                              docker:default
 => [internal] load .dockerignore                                                                                                       0.0s
 => => transferring context: 2B                                                                                                         0.0s
 => [internal] load build definition from Dockerfile.updateDevice                                                                       0.0s
 => => transferring dockerfile: 303B                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/python:alpine3.18                                                                    1.6s
 => [1/4] FROM docker.io/library/python:alpine3.18@sha256:a5d1738d6abbdff3e81c10b7f86923ebcb340ca536e21e8c5ee7d938d263dba1              1.3s
 => => resolve docker.io/library/python:alpine3.18@sha256:a5d1738d6abbdff3e81c10b7f86923ebcb340ca536e21e8c5ee7d938d263dba1              0.0s
 => => sha256:88f254778c15fc679ada404e96b578dd4d36c89bb77b32e2f46160e3a5e25c02 11.94MB / 11.94MB                                        0.7s
 => => sha256:7df9c8ac86de17d9ceef9cb874c6aa6ab0958650953e320b7ef2b9d6e2ad869b 240B / 240B                                              0.3s
 => => sha256:a5d1738d6abbdff3e81c10b7f86923ebcb340ca536e21e8c5ee7d938d263dba1 1.65kB / 1.65kB                                          0.0s
 => => sha256:dc2e8896e2bc0a52effa1249de614eee1b770a46cb1df25a72baf60a34ce5b1a 1.37kB / 1.37kB                                          0.0s
 => => sha256:a4c7645b18dcc60bfbcc654a5b813458da4d84f95f5ac86f98d97458ddf3d53b 6.04kB / 6.04kB                                          0.0s
 => => sha256:430548f4d4bf7cdf8dc1e14a535a6ae863ecace3300d9f2b84ced5df27d88721 622.32kB / 622.32kB                                      0.4s
 => => extracting sha256:430548f4d4bf7cdf8dc1e14a535a6ae863ecace3300d9f2b84ced5df27d88721                                               0.1s
 => => sha256:1b372ffb6da3534a6431f95b347de474c1762c10cf992d2972503ec44da7cbff 2.67MB / 2.67MB                                          0.7s
 => => extracting sha256:88f254778c15fc679ada404e96b578dd4d36c89bb77b32e2f46160e3a5e25c02                                               0.2s
 => => extracting sha256:7df9c8ac86de17d9ceef9cb874c6aa6ab0958650953e320b7ef2b9d6e2ad869b                                               0.0s
 => => extracting sha256:1b372ffb6da3534a6431f95b347de474c1762c10cf992d2972503ec44da7cbff                                               0.1s
 => [internal] load build context                                                                                                       0.0s
 => => transferring context: 972B                                                                                                       0.0s
 => [2/4] RUN mkdir -p /app /configFiles                                                                                                0.5s
 => [3/4] COPY update_server_device.py /app                                                                                             0.0s
 => [4/4] WORKDIR /app                                                                                                                  0.0s
 => exporting to image                                                                                                                  0.1s
 => => exporting layers                                                                                                                 0.1s
 => => writing image sha256:69320e5a1d5eb4d9ce6f8a788e4c383654eb784179c290bf8978b59e858d33b5                                            0.0s
 => => naming to docker.io/library/update_config:dev                                                                                    0.0s
@DemoSystem-NUC12SNKi72:~/automated-self-checkout$ sudo docker images
REPOSITORY              TAG          IMAGE ID       CREATED              SIZE
update_config           dev          69320e5a1d5e   11 seconds ago       51.8MB
bit_model_downloader    dev          95cf5a918171   About a minute ago   4.24GB
benchmark               igt          3f95a2547560   34 minutes ago       1.06GB
benchmark               xpu          327f5c844a54   36 minutes ago       495MB
benchmark               dev          e1b566d34ebf   37 minutes ago       1.07GB
openvino/model_server   2023.1-gpu   756c4f0f94fa   2 months ago         584MB

:::::Try 2::::
admin@DemoSystem-NUC12SNKi72:~/automated-self-checkout$ sudo make build-ovms-server
HTTPS_PROXY= HTTP_PROXY= docker pull openvino/model_server:2023.1-gpu
2023.1-gpu: Pulling from openvino/model_server
Digest: sha256:1da7d5e1b5ce1373f3da44c1e6e82b49803178acfdf06a24e692041fee665fc1
Status: Image is up to date for openvino/model_server:2023.1-gpu
docker.io/openvino/model_server:2023.1-gpu
sudo docker build --build-arg HTTPS_PROXY= --build-arg HTTP_PROXY= -f configs/opencv-ovms/models/2022/Dockerfile.updateDevice -t update_config:dev configs/opencv-ovms/models/2022/.
[+] Building 1.0s (9/9) FINISHED                                                                                                                                docker:default
 => [internal] load .dockerignore                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                           0.0s
 => [internal] load build definition from Dockerfile.updateDevice                                                                                                         0.0s
 => => transferring dockerfile: 303B                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/python:alpine3.18                                                                                                      0.8s
 => [1/4] FROM docker.io/library/python:alpine3.18@sha256:a5d1738d6abbdff3e81c10b7f86923ebcb340ca536e21e8c5ee7d938d263dba1                                                0.0s
 => [internal] load build context                                                                                                                                         0.0s
 => => transferring context: 45B                                                                                                                                          0.0s
 => CACHED [2/4] RUN mkdir -p /app /configFiles                                                                                                                           0.0s
 => CACHED [3/4] COPY update_server_device.py /app                                                                                                                        0.0s
 => CACHED [4/4] WORKDIR /app                                                                                                                                             0.0s
 => exporting to image                                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                                   0.0s
 => => writing image sha256:69320e5a1d5eb4d9ce6f8a788e4c383654eb784179c290bf8978b59e858d33b5                                                                              0.0s
 => => naming to docker.io/library/update_config:dev                                                                                                                      0.0s
admin@DemoSystem-NUC12SNKi72:~/automated-self-checkout$ sudo docker images
REPOSITORY                       TAG          IMAGE ID       CREATED          SIZE
update_config                    dev          69320e5a1d5e   18 minutes ago   51.8MB
bit_model_downloader             dev          95cf5a918171   19 minutes ago   4.24GB
benchmark                        igt          3f95a2547560   53 minutes ago   1.06GB
benchmark                        xpu          327f5c844a54   55 minutes ago   495MB
benchmark                        dev          e1b566d34ebf   55 minutes ago   1.07GB
openvino/ubuntu20_dev            latest       b600b1d40227   2 days ago       3.96GB
aler9/rtsp-simple-server         latest       b74e3e3b27e2   5 days ago       28.2MB
openvino/model_server            2023.1-gpu   756c4f0f94fa   2 months ago     584MB
ghcr.io/jqlang/jq                latest       ef28ad8d3716   2 months ago     2.33MB
openvino/ubuntu20_data_runtime   2021.4.2     73fcdb5b37c8   2 years ago      2.14GB

**Comment by jim-wang-intel** [comment]
@kk-vp  the documentation is out of date and will update the documentation
