### ISSUE TITLE
Spike: docker compose replica performance vs profile launcher

### ISSUE THREAD

**Issue by brian-intel** [intel-retail/automated-self-checkout#468]
Run each pipeline for 5 minutes and capture logs.

pipelines to run:
- GST (will need a new docker-compose)
- object-detection (existing [docker-compose](https://github.com/intel-retail/automated-self-checkout/blob/main/docker-compose.yml))
- capi_yolov5 (will need a new docker-compose)

**Comment by jim-wang-intel** [comment]
this issue is resolved as part of PR #470
