### ISSUE TITLE
Evaluate Automated Self Checkout with DL Pipeline Server

### ISSUE THREAD

**Issue by mechris1** [intel-retail/automated-self-checkout#597]
- [x] Replicate Automated Self Checkout pipeline in DL Pipeline Server (CPU, no parameters - basic)
- [ ] Run benchmarking
- [ ] Minimum system requirements to run and compare with our current solution.
- [ ] Report out findings/learnings

**Comment by brian-intel** [comment]
yolov5+efficientnet 3 pipelines			
						1			2			3			Avg
DLStreamer				30.01		29.98		30			29.99666667
EVAM single server		25.27458313	23.83788367	22.34245479	23.8183072
EVAM multiple servers	30.04973554	30.07119659	30.07410121	30.06501111

Full 3 pipelines			
						1			2			3			Avg
DLStreamer				22.86		23.58		19.01		21.81666667
EVAM single server		20.20177535	18.66237088	16.91272482	18.59229035
EVAM multiple servers	30.01848838	30.03958501	30.03400978	30.03069439

Docker stats		
						Memory Usage	Total for 3 servers MiB		Image size
DLStreamer				407.9MiB		1234.57						5.41GB
EVAM single server		886.6MiB		886.6						8.01GB
EVAM multiple servers	385.2MiB		1087						8.01GB
