### ISSUE TITLE
Server config Device is hard coded

### ISSUE THREAD

**Issue by brian-intel** [intel-retail/automated-self-checkout#63]
Find a method to support multiple device configurations in the OVMS server model config(configs/opencv-ovms/models/2022/config.json)

2 options
- Modify the config.json before launching OVMS server to match the user input
- Add CPU, GPU.0, GPU.1, GPU.2, GPU.3 to the current config.json to cover all currently supported configurations

**Comment by jim-wang-intel** [comment]
@brian-intel   Question: as i know ovms support [configuration updated in runtime](https://docs.openvino.ai/2023.0/ovms_docs_online_config_changes.html), will this still be an issue though?

**Comment by brian-intel** [comment]
Have the script modify the config.json with the target device on each startup
Shutdown the server everytime we run
