### ISSUE TITLE
gRPC IP needs to match OVMS server IP in Docker

### ISSUE THREAD

**Issue by brian-intel** [intel-retail/automated-self-checkout#64]
Make sure the OVMS client is using the OVMS server IP from Docker instead of localhost

**Comment by vli11** [comment]
it seems like we just need to guide user to use OVMS server IP for Docker on Client, why is it a bug?

**Comment by brian-intel** [comment]
The current implementation is using the host network so the hard coded 127.0.0.1 works. We will however run into issues in the future if we have multiple servers running. To make things more flexible and prevent the user from searching for Docker IP addresses we should grab the IP address based on the running containers name and pass it to the client container. Here is one way we can do this.

docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id
