### ISSUE TITLE
Text recognition path to the model is downloaded in the incorrect location

### ISSUE THREAD

**Issue by jstein13** [intel-retail/automated-self-checkout#71]
Example script: configs/dlstreamer/framework-pipelines/arc/yolov5s_full.sh
The script is looking for the text recognition model in: 
models/text-recognition-0012-GPU/1/FP16-INT8/text-recognition-0012-mod.xml

but the model is actually in this location on the host here (obscuring the volume mount path): 
<path of volume mount>/text-recognition-0012-GPU/text-recognition-0012-mod/1/FP16-INT8/text-recognition-0012-mod.*

Multiple scripts use this path to the text recognition model, so the modelDownloader script is probably what needs to be looked at

**Comment by brian-intel** [comment]
Run through the DLStreamer test plan
