### ISSUE TITLE
Add documentation for docker-run.sh Environment variables

### ISSUE THREAD

**Issue by brian-intel** [intel-retail/automated-self-checkout#73]
Add some documentation to discuss how to set the following settings if using docker-run only:

STREAM_DENSITY_MODE
RENDER_MODE
LOW_POWER
CPU_ONLY

**Comment by jim-wang-intel** [comment]
@brian-intel  is this for both 1.0.0 and 1.5.0?

**Comment by brian-intel** [comment]
We should get this merged into both

**Comment by jim-wang-intel** [comment]
The env has changed since 1.5.0 release and this list is out of dated. there is more envs available now for ovms docker-run. I think we should update the issue @brian-intel @vli11
